# Generated by Django 4.0.5 on 2022-06-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
