# Generated by Django 4.0.5 on 2022-06-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='meu_nome_de_tabela',
        ),
    ]
